# conda env create --file environment.yml --prefix ./env
# mamba env create --file environment.yml --prefix ./env
name: ecommerce_customer_churn_prevention
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - invoke
  - jupyter
  - jupyterlab
  - keras
  - xgboost
  - matplotlib
  - missingno
  - nbdime
  - numpy
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pip
  - plotly
  - pyjanitor
  - pylint
  - pyprojroot
  - python=3.11
  - python-dotenv
  - scikit-learn
  - seaborn
  - statsmodels
  - pytorch